name: Playwright API Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci

    - name: Run Playwright API tests
      run: npx playwright test
      env:
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        TEST_REGISTER_EMAIL: ${{ secrets.TEST_REGISTER_EMAIL }}
        TEST_REGISTER_PASSWORD: ${{ secrets.TEST_REGISTER_PASSWORD }}
        TEST_TODELETE_EMAIL: ${{ secrets.TEST_TODELETE_EMAIL }}
        TEST_TODELETE_PASSWORD: ${{ secrets.TEST_TODELETE_PASSWORD }}
        RB_ADMIN_LOGIN: ${{ secrets.RB_ADMIN_LOGIN }}
        RB_ADMIN_PASSWORD: ${{ secrets.RB_ADMIN_PASSWORD }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30